from typing import Dict, Any

from agents.agent_responses import AnalysisInsights


def populate_html_template(project: str,
                           insights: AnalysisInsights,
                           components_html: str,
                           cytoscape_json: Dict[str, Any]) -> str:
    """
    Populate an HTML template with data.

    Args:
        template (str): The HTML template as a string.
        data (dict): A dictionary containing the data to populate the template.

    Returns:
        str: The populated HTML string.
    """
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CodeBoarding Analysis - {project}</title>
    <!-- Load dagre first, then cytoscape, then cytoscape-dagre -->
    <script src="https://unpkg.com/dagre@0.8.5/dist/dagre.min.js"></script>
    <script src="https://unpkg.com/cytoscape@3.23.0/dist/cytoscape.min.js"></script>
    <script src="https://unpkg.com/cytoscape-dagre@2.4.0/cytoscape-dagre.js"></script>
    <style>
        body {{
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0 auto;
            padding: 20px;
            background-color: #f8f9fa;
        }}
        
        .component {{
            border-left: 3px solid #6c757d;
            padding-left: 15px;
            margin-bottom: 20px;
            background: white;
            padding: 15px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        
        .component h3 {{
            color: #495057;
            margin-top: 0;
        }}
        
        code {{
            background-color: #e9ecef;
            padding: 2px 4px;
            border-radius: 3px;
            font-family: monospace;
        }}
        
        #cy {{
            width: 100%;
            height: 600px;
            border: 1px solid #dee2e6;
            margin: 20px 0;
            border-radius: 8px;
            background-color: #ffffff;
        }}
        
        .badges {{
            margin: 20px 0;
        }}
        
        .badge {{
            display: inline-block;
            margin-right: 10px;
        }}
        
        .badge img {{
            vertical-align: middle;
        }}
        
        .references {{
            list-style: none;
            padding-left: 0;
            margin: 10px 0;
        }}
        
        .references li {{
            margin: 4px 0;
        }}
        
        .diagram-controls {{
            margin: 10px 0;
            text-align: center;
        }}
        
        .diagram-controls button {{
            margin: 0 5px;
            padding: 8px 16px;
            background: #6c757d;
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
        }}
        
        .diagram-controls button:hover {{
            background: #495057;
        }}
    </style>
</head>
<body>
    <h1>CodeBoarding Analysis{' - ' + project if project else ''}</h1>
    
    <div class="badges">
        <a href="https://github.com/CodeBoarding/GeneratedOnBoardings" class="badge">
            <img src="https://img.shields.io/badge/Generated%20by-CodeBoarding-9cf?style=flat-square" alt="Generated by CodeBoarding">
        </a>
        <a href="https://www.codeboarding.org/demo" class="badge">
            <img src="https://img.shields.io/badge/Try%20our-Demo-blue?style=flat-square" alt="Try our Demo">
        </a>
        <a href="mailto:contact@codeboarding.org" class="badge">
            <img src="https://img.shields.io/badge/Contact%20us%20-%20contact@codeboarding.org-lightgrey?style=flat-square" alt="Contact us">
        </a>
    </div>
    
    <div class="diagram-controls">
        <button onclick="resetLayout()">Reset Layout</button>
        <button onclick="fitToView()">Fit to View</button>
        <button onclick="exportImage()">Export PNG</button>
    </div>
    
    <div id="cy"></div>
    
    <h2>Details</h2>
    <p>{insights.description}</p>
    
    {components_html}
    
    <h3><a href="https://github.com/CodeBoarding/GeneratedOnBoardings/tree/main?tab=readme-ov-file#faq">FAQ</a></h3>
    
    <script>
        // Wait for all scripts to load before initializing
        document.addEventListener('DOMContentLoaded', function() {{
            // Check if all required libraries are loaded
            if (typeof cytoscape === 'undefined') {{
                console.error('Cytoscape is not loaded');
                document.getElementById('cy').innerHTML = '<div style="padding: 20px; text-align: center; color: #666;">Error loading diagram. Please refresh the page.</div>';
                return;
            }}
            
            if (typeof dagre === 'undefined') {{
                console.error('Dagre is not loaded');
                document.getElementById('cy').innerHTML = '<div style="padding: 20px; text-align: center; color: #666;">Error loading diagram. Please refresh the page.</div>';
                return;
            }}
            
            if (typeof cytoscapeDagre === 'undefined') {{
                console.error('Cytoscape-dagre extension is not loaded');
                document.getElementById('cy').innerHTML = '<div style="padding: 20px; text-align: center; color: #666;">Error loading diagram. Please refresh the page.</div>';
                return;
            }}
            
            // Register the dagre extension
            try {{
                cytoscape.use(cytoscapeDagre);
                console.log('Dagre extension registered successfully');
            }} catch (e) {{
                console.error('Failed to register dagre extension:', e);
                document.getElementById('cy').innerHTML = '<div style="padding: 20px; text-align: center; color: #666;">Error loading diagram. Please refresh the page.</div>';
                return;
            }}
            
            const cytoscapeData = {cytoscape_json};
            
            try {{
                const cy = cytoscape({{
                    container: document.getElementById('cy'),
                    
                    elements: cytoscapeData.elements,
                    
                    style: [
                        {{
                            selector: 'node',
                            style: {{
                                'background-color': '#f8f9fa',
                                'label': 'data(label)',
                                'text-valign': 'center',
                                'text-halign': 'center',
                                'color': '#495057',
                                'text-wrap': 'wrap',
                                'font-size': '11px',
                                'font-weight': '500',
                                'width': 'label',
                                'height': 'label',
                                'padding': '15px',
                                'shape': 'roundrectangle',
                                'border-width': 2,
                                'border-color': '#dee2e6'
                            }}
                        }},
                        {{
                            selector: 'node[hasLink = true]',
                            style: {{
                                'background-color': '#e9ecef',
                                'border-color': '#6c757d',
                                'cursor': 'pointer',
                                'border-width': 3
                            }}
                        }},
                        {{
                            selector: 'node:hover',
                            style: {{
                                'background-color': '#dee2e6',
                                'border-color': '#495057',
                                'border-width': 3
                            }}
                        }},
                        {{
                            selector: 'edge',
                            style: {{
                                'width': 2,
                                'line-color': '#adb5bd',
                                'target-arrow-color': '#adb5bd',
                                'target-arrow-shape': 'triangle',
                                'curve-style': 'bezier',
                                'label': 'data(label)',
                                'font-size': '10px',
                                'color': '#6c757d',
                                'text-rotation': 'autorotate',
                                'text-margin-y': -10,
                                'text-background-color': '#ffffff',
                                'text-background-opacity': 0.8,
                                'text-background-padding': '2px',
                                'text-background-shape': 'roundrectangle'
                            }}
                        }}
                    ],
                    
                    layout: {{
                        name: 'dagre',
                        directed: true,
                        padding: 30,
                        rankDir: 'LR',
                        nodeSep: 80,
                        edgeSep: 20,
                        rankSep: 150
                    }}
                }});
                
                // Apply dagre layout after cytoscape is initialized
                cy.layout({{
                    name: 'dagre',
                    directed: true,
                    padding: 30,
                    rankDir: 'LR',
                    nodeSep: 80,
                    edgeSep: 20,
                    rankSep: 150
                }}).run();
                
                // Add click handler for nodes with links
                cy.on('tap', 'node[hasLink = true]', function(evt) {{
                    const node = evt.target;
                    const linkUrl = node.data('linkUrl');
                    if (linkUrl) {{
                        window.open(linkUrl, '_blank');
                    }}
                }});
                
                // Add simple tooltip on hover
                cy.on('mouseover', 'node', function(evt) {{
                    const node = evt.target;
                    const description = node.data('description');
                    if (description) {{
                        // Simple tooltip implementation
                        const tooltip = document.createElement('div');
                        tooltip.innerHTML = description;
                        tooltip.style.cssText = `
                            position: fixed;
                            background: #333;
                            color: white;
                            padding: 8px;
                            border-radius: 4px;
                            font-size: 12px;
                            max-width: 300px;
                            z-index: 1000;
                            pointer-events: none;
                        `;
                        document.body.appendChild(tooltip);
                        
                        const updateTooltip = (e) => {{
                            tooltip.style.left = (e.clientX + 10) + 'px';
                            tooltip.style.top = (e.clientY + 10) + 'px';
                        }};
                        
                        document.addEventListener('mousemove', updateTooltip);
                        
                        node.on('mouseout', () => {{
                            document.removeEventListener('mousemove', updateTooltip);
                            if (tooltip.parentNode) {{
                                tooltip.parentNode.removeChild(tooltip);
                            }}
                        }});
                    }}
                }});
                
                // Make control functions globally available
                window.resetLayout = function() {{
                    cy.layout({{
                        name: 'dagre',
                        directed: true,
                        padding: 30,
                        rankDir: 'LR',
                        nodeSep: 80,
                        edgeSep: 20,
                        rankSep: 150
                    }}).run();
                }};
                
                window.fitToView = function() {{
                    cy.fit();
                }};
                
                window.exportImage = function() {{
                    const png64 = cy.png({{ scale: 2, full: true }});
                    const link = document.createElement('a');
                    link.download = 'diagram.png';
                    link.href = png64;
                    link.click();
                }};
                
            }} catch (error) {{
                console.error('Error initializing Cytoscape:', error);
                document.getElementById('cy').innerHTML = '<div style="padding: 20px; text-align: center; color: #666;">Error loading diagram. Please refresh the page.</div>';
            }}
        }});
    </script>
</body>
</html>"""
